version: '3.8'

services:
  app:
    image: laravelsail/php82-composer:latest
    container_name: sendportal_app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      SERVICE_NAME: app
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: sendportal
      DB_USERNAME: sendportal_user
      DB_PASSWORD: sendportal_pass
    command: >
      sh -c "
        composer install &&
        php artisan key:generate &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=80
      "

  mysql:
    image: mysql:8.0
    container_name: sendportal_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sendportal
      MYSQL_USER: sendportal_user
      MYSQL_PASSWORD: sendportal_pass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
